apiVersion: argoproj.io/v1alpha1  # Changed from apps/v1
kind: Rollout                     # Changed from Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: immersion-demo
spec:
  replicas: {{ .Values.result.replicaCount }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result
        name: result
        ports:
        - containerPort: 80
          name: result
        resources:
          requests:
            cpu: {{ .Values.result.resources.cpu }}
            memory: {{ .Values.result.resources.memory }}
  strategy:
    blueGreen:  # Changed from rollingUpdate or recreate
      activeService: voting-app-result
      previewService: voting-app-result-preview
