apiVersion: argoproj.io/v1alpha1  # Changed from apps/v1
kind: Rollout                     # Changed from Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: immersion-demo
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: worker
        resources:
          requests:
            cpu: {{ .Values.worker.resources.cpu }}
            memory: {{ .Values.worker.resources.memory }}
  strategy:
    blueGreen:  # Changed from rollingUpdate or recreate
      activeService: voting-app-worker
      previewService: voting-app-worker-preview
